### ISSUE TITLE
Explorer layout is broken in Chrome on Ubuntu Linux

### ISSUE THREAD

**Issue by savinov** [tarantool/graphqlide#43]
Tarantool Enterprise 2.8.3-0-g01023dbc2-r445

Ubuntu 18.04.6 LTS

'graphqlapi == 0.0.7-1'
'graphqlapi-helpers == 0.0.7-1'
'graphqlide == 0.0.18-1'

![image](https://user-images.githubusercontent.com/711887/152758112-2aad5d66-a0a3-4e05-b617-37d4f19bcd7a.png)
![image](https://user-images.githubusercontent.com/711887/152758213-164395d7-a997-4f92-8f02-f091c072e50d.png)

**Comment by no1seman** [comment]
closed by: https://github.com/tarantool/graphqlide/commit/4bedd6b69d4d0ea5df7b55cdf168c2e60475b2d1
